
# 포트 바꾸는 방법
#server:
#  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/basic
    username: root
    password: 1234
  jpa:
    database : mysql
    # innoDB 사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    # 테이블은 생성해주나, 스키마는 반드시 사전에 생성 필요
    generate-ddl: true
    # jpa는 인터페이스이고, hibernate는 구현체이다. (실질적 기능 구현)
    hibernate:
      # create 옵션은 매번 table을 drop 후 재생성
      # update 옵션은 변경 사항만 alter를 적용하고 기존의 데이터 유지
      # validate는 실제 DB와의 차이만을 check => 반영을 안한다는 얘기. 에러를 발생시킨다.
      # 로컬에서 작업할때는 update 아니면, create
      # 변경 사항 중에 **주로 추가 사항만을 반영**하고, **삭제나 수정사항**은 반영 안되는 경우도 있음, 특히 어노테이션에 거는 옵션 이런거
      # 꿀팁: 스키마가 확정되기 전까지는 create로 작업하다가 그 이후 update로 놓고 작업
      ddl-auto: update
      # 콘솔창에 ddl, dml문을 출력하여 보여주는 옵션이다.
      # 실무에서는 로그를 다 파일로 관리한다 => 따라서 실무에선 안켜놓는게 좋음...
    show_sql: true


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

